### ISSUE TITLE
ApplicationRequest object has no attribute 'get_array' 

### ISSUE THREAD

**Issue by robline** [pyexcel/pyramid-excel#2]
I'm using the following versions on Ubuntu 14.04:
**pyexcel-xls == 0.1.0
pyramid-excel == 0.0.2
pyramid==1.4.5**

I've been following the quick start tutorial, with two exceptions. I moved the following block to my app's __init__.py :
**if __name__ == '__main__':**
    [...]

I also put the view code into existing add views. (however the same error occurs if I follow the tutorial exactly).

When I hit the url, the upload form displays properly. I select an .xls file and click upload. I get an AttributeError: 'ApplicationRequest' object has no attribute 'get_array' error.

Below is the traceback:

(samples_prod) rob@ubuntu:~/development/samples_prod/samples_prod$ pserve devepment.ini 
Starting server in PID 3771.
serving on http://0.0.0.0:6553
2016-03-16 10:39:05,417 ERROR [pyramid_debugtoolbar][Dummy-1] Exception at http://0.0.0.0:6553/samples/bulk_import_add
traceback url: http://0.0.0.0:6553/samples/_debug_toolbar/exception?token=[...]
Traceback (most recent call last):
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 172, in toolbar_tween
    response = _handler(request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 55, in resource_timer_handler
    result = handler(request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/config/views.py", line 237, in _secured_view
    return view(context, request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/rob/development/samples_prod/samples_prod/samples/views/bulk_imports.py", line 54, in add
    data = request.get_array(field_name='file')
**AttributeError: 'ApplicationRequest' object has no attribute 'get_array'**

2016-03-16 10:39:05,418 ERROR [waitress][Dummy-1] Exception when serving /samples/bulk_import_add
Traceback (most recent call last):
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 195, in toolbar_tween
    response = request.invoke_subrequest(subrequest)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/rob/.virtualenvs/samples_prod/local/lib/python2.7/site-packages/pyramid/router.py", line 159, in handle_request
    raise HTTPNotFound(msg)
HTTPNotFound: /samples/_debug_toolbar/exception

**Comment by chfw** [comment]
This sounds like the request object has not been overloaded with get_array method. In other words, (this line)[https://github.com/pyexcel/pyramid-excel/blob/master/pyramid_excel/__init__.py#L70] was not called. Have you done this in your development.ini

    pyramid.includes = pyramid_excel

or did this in your main.py:

    config = Configurator(.....)
    config.include('pyramid_excel')

**Comment by robline** [comment]
Thanks for the fast response!  Here is the relevant part of __init__.py:

config = Configurator(settings=settings,
                        session_factory=my_session_factory,
                        root_factory='samples.security.RootFactory',
                        authentication_policy=authentication_policy,
                        authorization_policy=authorization_policy)

    # support for bulk upload of freezer/sample spreadsheets --robline
    config.include('pyramid_excel')
    config.scan()

**Comment by chfw** [comment]
What you are doing is OK. Now, I suspect the following line may have been overrided by other extensions.

     config.set_request_factory(ExcelRequestFactory)

for example, other extension will call set_request_factory(....), which will remove ExcelRequestFactory..

does the quick start code work? http://pyramid-excel.readthedocs.org/en/latest/#quick-start

**Comment by robline** [comment]
Thanks again. the quick start code led to the same issue but I am really new to Pyramid so I may be overlooking something. 

I did not find the line below anywhere in my code nor in the docs:
 config.set_request_factory(ExcelRequestFactory)

when I add it to init.py I get:
File "/home/rob/development/samples_prod/samples_prod/samples/__init__.py", line 50, in main
    config.set_request_factory(ExcelRequestFactory)
NameError: global name 'ExcelRequestFactory' is not defined

**Comment by robline** [comment]
I did notice that when I pip installed pyramid-excel instead of using requirements.txt, it upgraded my pyramid from 1.4.5 to 1.6.1. This breaks other things. Does pyramid-excel depend on 1.6.x?

**Comment by chfw** [comment]
well that line is in the extension. 

pyramid-excel was tested against 1.5.4. And the latest test was done using 1.6 , https://travis-ci.org/pyexcel/pyramid-excel/jobs/105298617 .. 

That could be the problem. Can you upgrade it to 1.6.x and see?

**Comment by robline** [comment]
upgrading breaks my existing apps but when I do eventually upgrade them I'll try it. Thanks for your help. You can close this or leave it open.

**Comment by chfw** [comment]
That's a pity. In order to roll back, I don't know when it will be done. For now, you have the choice to look at these alternatives: https://github.com/lxneng/pyramid_tablib or you can use [pyexcel](http://pyexcel.readthedocs.org/en/latest/) itself.

**Comment by robline** [comment]
thanks!  I'm also looking into upgrading which must be done.

**Comment by chfw** [comment]
Hi, robline, could you please try this:

    pip install https://github.com/pyexcel/pyramid-excel/archive/master.zip


I tried the quick start example with pyramid 1.4.5 and it worked for me.

**Comment by chfw** [comment]
Just made 0.0.3 release which had a more accurate dependencies in setup.py. so you as well try 

    pip install pyramid-excel==0.0.3

[This build](https://travis-ci.org/pyexcel/pyramid-excel/builds/116519925) proves it is compatible with 1.4.9.

**Comment by robline** [comment]
You helped me solve this. There was indeed another excel-based extension in the codebase.
